### ISSUE TITLE
Tag 1.0.0

### ISSUE THREAD

**Issue by tmcw** [tmcw/simple-statistics#82]
This has been stable for a long time and I'm comfortable with the layout of the API. I should tag 1.0.0.

**Comment by plato-cambrian** [comment]
Hi, please consider improving the variance calculation to handle low-variance floating point numbers:

https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Computing_shifted_data

**Comment by tmcw** [comment]
Split that into #83 - I'm happy to add features _after_ 1.0.0 but pretty confident we can release 1.0.0 with the current featureset.

**Comment by tmcw** [comment]
Folding into #105
