### ISSUE TITLE
Calculations incorrect.

### ISSUE THREAD

**Issue by wgmueller** [tmcw/simple-statistics#86]
console.log(stat.variance([1,2.0,3,4,5,6,7]))
4
console.log(stat.standard_deviation([1,2,3.0,4,5,6,7]))
2

**Comment by tmcw** [comment]
Reopening & reverting: @wgmueller are you sure you're not looking for `sample_variance`?

**Comment by tmcw** [comment]
Behavior of variance matches [the wikipedia definition](http://en.wikipedia.org/wiki/Variance#Fair_die).

**Comment by wgmueller** [comment]
Oh ok.  You're right whenever I see variance I think sample variance.  Sorry.
