### ISSUE TITLE
jenksBreaks() is incorrect

### ISSUE THREAD

**Issue by Joker-vD** [tmcw/simple-statistics#88]
A simple test: jenks([9,10,11,12,13], 5) returns [9,null,9,10,11,13] instead of expected [9,10,11,12,13,13].

More sophisticated case: jenks([2,32,33,34,100], 3) returns [2,2,32,100] instead of expected [2,32,100,100].

(Also, what does one need the upper bound for in the breaks?)

Anyway, the fix is as following:

    diff --git a/simple_statistics.js b/simple_statistics.js
    index 46fb5c9..076cd7f 100644
    --- a/simple_statistics.js
    +++ b/simple_statistics.js
    @@ -963,19 +963,18 @@
         // and derive an array of n breaks.
         function jenksBreaks(data, lower_class_limits, n_classes) {
     
    -        var k = data.length - 1,
    +        var k = data.length,
                 kclass = [],
                 countNum = n_classes;
     
    -        // the calculation of classes will never include the upper and
    -        // lower bounds, so we need to explicitly set them
    +        // the calculation of classes will never include the upper
    +        // bound, so we need to explicitly set it
             kclass[n_classes] = data[data.length - 1];
    -        kclass[0] = data[0];
     
             // the lower_class_limits matrix is used as indices into itself
             // here: the `k` variable is reused in each iteration.
    -        while (countNum > 1) {
    -            kclass[countNum - 1] = data[lower_class_limits[k][countNum] - 2];
    +        while (countNum > 0) {
    +            kclass[countNum - 1] = data[lower_class_limits[k][countNum] - 1];
                 k = lower_class_limits[k][countNum] - 1;
                 countNum--;
             }

First, the lower_class_limits does include the lower bound (the first cluster always starts at the first element, duh). Second, the value of lower_class_limits[N][M] answers question "If we break the first N points of data into M clusters, what's the starting index of the last cluster?", so we should start from the row lower_class_limits[data.length], and work our way up to lower_class_limits[1].

**Comment by tmcw** [comment]
Any chance you can submit that fix as a pull request?

**Comment by Joker-vD** [comment]
Submitted as a pull request.
