### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by el-feo** [tmcw/simple-statistics#90]
I apologize in advance for posting this on the issues page if not appropriate.
I'm having difficulty troubleshooting a site loading on mobile Safari and Chrome on the iPhone/iPad in which I'm using simple-statistics.  Are there any known compatibility issues with mobile browsers?

**Comment by emomoh** [comment]
No.

Emmanuel

**Comment by el-feo** [comment]
Thank you.  I just narrowed it down to this: "Intl.NumberFormat" not being compatible with mobile, it was not simple-statistics.
